export const CHANGE_INPUT = 'CHANGE_INPUT';
export const INITIALIZE_AUTH_INPUTS = 'INITIALIZE_AUTH_INPUTS';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const REQUEST_READY = 'REQUEST_READY';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const CHECK = 'CHECK';
export const CHECK_SUCCESS = 'CHECK_SUCCESS';
export const CHECK_FAILURE = 'CHECK_FAILURE';

export const TEMP_LOGIN = 'TEMP_LOGIN';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const CONTENT_CHANGE = 'CONTENT_CHANGE';

export const WRITE_MEMO = 'WRITE_MEMO';
export const WRITE_MEMO_SUCCESS = 'WRITE_MEMO_SUCCESS';
export const WRITE_MEMO_FAILURE = 'WRITE_MEMO_FAILURE';

export const GET_MEMO = 'GET_MEMO';
export const GET_MEMO_SUCCESS = 'GET_MEMO_SUCCESS';
export const GET_MEMO_FAILURE = 'GET_MEMO_FAILURE';

export const MAKE_UPDATE_MODE = 'MAKE_UPDATE_MODE';
export const MAKE_NO_UPDATE_MODE = 'MAKE_NO_UPDATE_MODE';

export const UPDATE_MEMO = 'UPDATE_MEMO';
export const UPDATE_MEMO_SUCCESS = 'UPDATE_MEMO_SUCCESS';
export const UPDATE_MEMO_FAILURE = 'UPDATE_MEMO_FAILURE';

export const REMOVE_MEMO = 'REMOVE_MEMO';
export const REMOVE_MEMO_SUCCESS = 'REMOVE_MEMO_SUCCESS';
export const REMOVE_MEMO_FAILURE = 'REMOVE_MEMO_FAILURE';