export const CHANGE_INPUT = 'CHANGE_INPUT';
export const CHANGE_INPUT_SUCCESS = 'CHANGE_INPUT_SUCCESS';
export const CHANGE_INPUT_FAILURE = 'CHANGE_INPUT_FAILURE';
export const INITIALIZE_AUTH_INPUTS = 'INITIALIZE_AUTH_INPUTS';
